services:
  - type: web
    name: foodguide
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn foodguide.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foodguide-db
          property: connectionString

databases:
  - name: foodguide-db
    plan: free
