services:
  - type: web
    name: foodguide
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py createsuperuser --noinput  # Создание суперпользователя
    startCommand: gunicorn foodguide.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foodguide-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"  # Имя суперпользователя
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"  # Почта суперпользователя
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "admin"  # Пароль суперпользователя


databases:
  - name: foodguide-db
    plan: free
